### ISSUE TITLE
Question on IOS STF and its working

### ISSUE THREAD

**Issue by AmandeepT** [nanoscopic/stf_ios_support#109]
I am trying to install IOS STF using a MAC (Xcode-12.5.1, cloned web repo from one of the project) and Ubuntu 18.4 machine. I tried to follow the steps for both provider and server machine but can't see the any device (tried iPhone Xs (ios-14.5.1) and 12 (ios-14.7.1) **but can't see any device**.

**1. Please let me know if we really need two machines for this step up.
2. what all other steps I need to follow to get this working.**

![image](https://user-images.githubusercontent.com/79556814/129458393-a8370f16-3e35-41b7-9271-a96d22ea310a.png)

**Comment by KostyaSha** [comment]
https://github.com/DeviceFarmer/stf_ios_support#debugging

**Comment by nanoscopic** [comment]
@KostyaSha This is another inappropriate comment. Don't insult people attempting to use the system.

@AmandeepT You don't need to use two machines. You can do everything on one if desired.

The documentation is there but I agree it is not clear and is difficult to understand. It has also not really been updated in years. If you still care about this project, keep a look out as new updates will be coming.

The general answer is that iOS support for STF is currently in a messy state of disrepair having not been maintained for a few years. @KostyaSha has been attempting to get it to work again, and I will be doing so as well.

I'm closing this ticket for now, as this issue is ancient and I am not sure you are trying to use this code any more. If you are, please reopen the ticket and explain the current result you are seeing.
