### ISSUE TITLE
Question on idb

### ISSUE THREAD

**Issue by letsautom8** [nanoscopic/stf_ios_support#87]
Appreciate your efforts on ios support. Is there a plan to move away from webdriveragent to FB's idb in the future?

**Comment by nanoscopic** [comment]
Considering that WDA is deprecated and Facebook has moved on to idb, yes.

That said I have not had success running idb against real devices thus far. I have not tried now for several months though. They may have fixed it since I last tried.

It is somewhat important to move to idb in order to support virtual IOS devices. Facebook reversed engineered a lot of the internals of simulators and added custom stuff ( such as for streaming out video from simulators )

I am still working on things related to stf_ios_support for multiple groups now... so the work will be continuing despite TMobile dropping the project. It is just much more dependent on the investment of my free time now.

**Comment by rounakcodes** [comment]
User interface input works only on simulators with idb, not on real devices. So, we still need WDA.

**Comment by nanoscopic** [comment]
That is my experience with idb yes. I was not able to get input control to work against real devices.

As I have, though, said, for best simulator control and to be able to have simulator video, idb will be needed.

Also, WDA itself isn't necessarily needed to do what stf_ios_support does. Some stripped down variant could be created. The only crucial bits of WDA used by stf_ios_support for synthetic event creation, keyboard events, and home functionality. WDA includes many other things that aren't used and could be dropped to make it less complicated and more streamlined to the use case.

**Comment by nanoscopic** [comment]
idb is for simulators. This project does not support simulators. Now that this is being updated I will likely integrate some usage of go-ios and that is partly similar to what idb conceptually helps with.
